# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5bfd4a01be2eef3dbe7731427a4046ced449758c0aa7a256675cd9e387ec06b238f6d60f4d3cfc308f7a575761e2c2e4b69e618bba36576ca7a4f2959a797fc

test:
  secret_key_base: 178ba0f54fc43847be1ec738ceb50010df373ddb5098246c0b50b5e3df2879acdc63cdaceb8a204a34b4aee8743398f7c6e6f988583118226473200fe757521b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
